version: "3.8"

services:
  nginx:
    image: nginx:1.19.8
    networks:
      - my-network
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx
    ports:
      - 8181:80

networks:
  my-network:
